### ISSUE TITLE
CVS issues

### ISSUE THREAD

**Issue by peol** [qlik-oss/core-assisted-prescription-auth#14]
Security scan found three vulnerabilities: https://cloud.docker.com/app/qlikea/repository/registry-1.docker.io/qlikea/qliktive-authentication-service/tags/0.0.1-49

Two of these are from our base image, we may want to use `node:8` which I believe these are fixed in.

The last one comes from bash that we are installing in `Dockerfile`.

**Comment by wennmo** [comment]
Closing issue
